Repository paritytech/statemint, pull requests merged in 2021-05, with the labels that each got.

#45 Jesse removal miss block
  pallets/collator-selection/src/benchmarking.rs
  pallets/collator-selection/src/lib.rs
  pallets/collator-selection/src/mock.rs
  pallets/collator-selection/src/tests.rs
  pallets/collator-selection/src/weights.rs
  runtime/statemine/src/lib.rs
  runtime/statemine/src/weights/pallet_collator_selection.rs
  runtime/statemint/src/lib.rs
  runtime/statemint/src/weights/pallet_collator_selection.rs
Labels: A3-inprogress, A6-mustntgrumble

#53 change ed in readme
  README.md
Labels: A2-insubstantial, B0-silent, C1-low

#62 Remove Sudo from Production Runtimes
  Cargo.lock
  node/src/chain_spec.rs
  runtime/statemine/Cargo.toml
  runtime/statemine/src/lib.rs
  runtime/statemint/Cargo.toml
  runtime/statemint/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#69 Update origins to Council
  runtime/statemine/src/lib.rs
  runtime/statemint/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#78 Runtime Cleanups
  node/src/chain_spec.rs
  runtime/statemine/src/constants.rs
  runtime/statemine/src/lib.rs
  runtime/statemint/src/constants.rs
  runtime/statemint/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low
